-- MySQL Script generated by MySQL Workbench
-- mar 14 may 2024 20:30:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Autor` (
  `idAutor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idAutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Genero` (
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Libro` (
  `ISBN` VARCHAR(13) NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `Autor` INT NOT NULL,
  `anyo` INT NOT NULL,
  `Genero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ISBN`),
  INDEX `fk_Libro_Autor_idx` (`Autor` ASC) VISIBLE,
  INDEX `fk_Libro_Genero1_idx` (`Genero` ASC) VISIBLE,
  CONSTRAINT `fk_Libro_Autor`
    FOREIGN KEY (`Autor`)
    REFERENCES `mydb`.`Autor` (`idAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Libro_Genero1`
    FOREIGN KEY (`Genero`)
    REFERENCES `mydb`.`Genero` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EjemplaresDisponibles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EjemplaresDisponibles` (
  `disponibles` INT NOT NULL,
  `Libro_ISBN` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`disponibles`, `Libro_ISBN`),
  INDEX `fk_EjemplaresDisponibles_Libro1_idx` (`Libro_ISBN` ASC) VISIBLE,
  CONSTRAINT `fk_EjemplaresDisponibles_Libro1`
    FOREIGN KEY (`Libro_ISBN`)
    REFERENCES `mydb`.`Libro` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Socio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Socio` (
  `idSocio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NULL,
  `telefono` VARCHAR(9) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idSocio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Prestamo` (
  `EjemplaresDisponibles_disponibles` INT NOT NULL,
  `EjemplaresDisponibles_Libro_ISBN` VARCHAR(13) NOT NULL,
  `Socio_idSocio` INT NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `isDevuelto` TINYINT NULL,
  PRIMARY KEY (`EjemplaresDisponibles_disponibles`, `EjemplaresDisponibles_Libro_ISBN`, `Socio_idSocio`, `fecha_inicio`),
  INDEX `fk_EjemplaresDisponibles_has_Socio_Socio1_idx` (`Socio_idSocio` ASC) VISIBLE,
  INDEX `fk_EjemplaresDisponibles_has_Socio_EjemplaresDisponibles1_idx` (`EjemplaresDisponibles_disponibles` ASC, `EjemplaresDisponibles_Libro_ISBN` ASC) VISIBLE,
  CONSTRAINT `fk_EjemplaresDisponibles_has_Socio_EjemplaresDisponibles1`
    FOREIGN KEY (`EjemplaresDisponibles_disponibles` , `EjemplaresDisponibles_Libro_ISBN`)
    REFERENCES `mydb`.`EjemplaresDisponibles` (`disponibles` , `Libro_ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EjemplaresDisponibles_has_Socio_Socio1`
    FOREIGN KEY (`Socio_idSocio`)
    REFERENCES `mydb`.`Socio` (`idSocio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
